apiVersion: apps/v1
kind: Deployment
metadata:
  name: solver-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: solver-operator
  template:
    metadata:
      labels:
        name: solver-operator
    spec:
      serviceAccountName: solver-operator
      containers:
        - name: solver-operator
          image: quay.io/goern/solver-operator
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - solver-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "solver-operator"
