apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: solver-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - "batch"
  resources:
  - "jobs"
  verbs:
  - "*"
- apiGroups:
  - thoth.ninja
  resources:
  - "*"
  verbs:
  - "*"
